## Preliminary Schedule

- 8:00-8:15 am: Introductory remarks, housekeeping (schedule, materials, etc, presentation)
- 8:15-9:15 am:  Introduction to resource-selection functions and species distribution models (John based on Movebank talk IntroRSFandSDM.pdf, presentation)
- 9:15-10:15 am: Step-selection functions and integrated step-selection functions (Tal, presentation)
- 10:15-10:30 am: break
- 10:30-12:00 am: Introduction to the amt package, coding resource and step-selection functions (Johannes, coding) 
- 12:00-1:30 pm: Lunch
- 1:30-2:30 pm: Modeling among-animal variability using 2-step methods and mixed-effects models (John, presentation)
- 2:30-3:30 pm: Implementation of ME: RSF and SSF (Johannes, coding) (-> SSF creating strata variable, aim: 30 min illustration and 30 min practicing and questions, play with otter data -> solutions)
- 3:30-4:00 pm: Predicting from RSFs and SSFs (Tal, presentation)
- 4:00-4:30 pm: Validating SSFs using unchplots (John, presentation)
- 4:30-5:00 pm: Questions

